import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'
import type { ReportRecord } from '@/lib/reports/store'
import type { StormEvent } from '@/lib/storms/mock-data'

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: 'Helvetica' },
  title: { fontSize: 20, fontWeight: 700, marginBottom: 6 },
  subtitle: { fontSize: 12, color: '#4b5563' },
  section: { marginTop: 18 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 6, color: '#111827' },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  label: { color: '#6b7280' },
  value: { color: '#111827' },
  callout: { marginTop: 12, padding: 12, borderRadius: 6, backgroundColor: '#eef2ff' },
  footer: { marginTop: 24, borderTop: '1px solid #e5e7eb', paddingTop: 8, color: '#6b7280', fontSize: 9 },
})

function miles(meters: number | null) {
  if (meters == null) return 'N/A'
  return `${(meters / 1609.34).toFixed(1)} mi`
}

export function StormReportDocument({ report, event }: { report: ReportRecord; event: StormEvent }) {
  const generatedAt = new Date(report.createdAt)
  const start = new Date(event.startTime)
  const end = new Date(event.endTime)
  const impactStatement = report.impacted
    ? 'This property falls within a confirmed storm impact zone based on storm polygon analysis.'
    : `This property is outside confirmed impact zones. Nearest confirmed zone is approximately ${miles(report.distanceToPolygonM)} away.`

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>Storm Impact Verification Report</Text>
        <Text style={styles.subtitle}>{report.address}</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Report Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Storm Event ID</Text>
            <Text style={styles.value}>{event.id}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date Generated</Text>
            <Text style={styles.value}>{generatedAt.toLocaleString()}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Storm Summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Impact window</Text>
            <Text style={styles.value}>{`${start.toLocaleString()} – ${end.toLocaleString()}`}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Storm type</Text>
            <Text style={styles.value}>{event.type.toUpperCase()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Max hail size</Text>
            <Text style={styles.value}>{event.maxHailSizeIn ? `${event.maxHailSizeIn}"` : 'N/A'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Max wind speed</Text>
            <Text style={styles.value}>{event.maxWindSpeedMph ? `${event.maxWindSpeedMph} mph` : 'N/A'}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Severity score</Text>
            <Text style={styles.value}>{event.severityScore}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Impact Statement</Text>
          <View style={styles.callout}>
            <Text>{impactStatement}</Text>
          </View>
          <View style={{ marginTop: 8 }}>
            <Text style={styles.label}>Geo verification</Text>
            <Text style={styles.value}>{`${report.lat.toFixed(5)}, ${report.lon.toFixed(5)}`}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Map Snapshot</Text>
          <Text style={styles.subtitle}>Placeholder — add map image export when provider integration lands.</Text>
        </View>

        <Text style={styles.footer}>
          Generated by TempestIQ · {generatedAt.toISOString()} · Storm Intelligence & Proof System
        </Text>
      </Page>
    </Document>
  )
}
